Documentation kustomize-helm-transformer
openinfradev/kustomize-helm-transformer pull request #24
Opened 2020-12-21 05:43 UTC by jabbukka

* add more documents for `contribution`, `quick start`, `code of conduct` and so on.

2021-01-04 07:36 UTC, Jaesang commented on docs/code_of_conduct.md
> +We as members, contributors, and leaders pledge to make participation in our
TEXT만 보면 줄바꿈을 our / community 이렇게 하고 있는데, 웹브라우저에서 렌더링된 Md파일을 보면 둘을 붙여주고 있네요. 무엇때문에 이렇게 되는건가요?

2021-01-04 07:37 UTC, jabbukka commented on docs/code_of_conduct.md
> +We as members, contributors, and leaders pledge to make participation in our
markdown 문법에서는 enter(개행문자) 하나로는 줄바꿈이 되지 않습니다. markdown에서 줄바꿈을 하기 위해서는 space 2개 연속 or enter 두번 연속 이어야 합니다.

2021-01-04 07:42 UTC, Jaesang requested changes

2021-01-04 07:42 UTC, Jaesang commented on docs/contribution.md
> +If there are no similar issues, you can create new issue [here](https://github.com/openinfradev/kustomize-helm-transformer/issues).
[here] 라고 동일링크가 두번 나오는데 둘 중에 하나만 살리는게 어떨까요

2021-01-04 07:43 UTC, Jaesang commented on docs/code_of_conduct.md
> +We as members, contributors, and leaders pledge to make participation in our
줄바꿈 상관없이 그냥 쭉쭉 엔터치면서 써도 되겠네요.

2021-01-04 07:50 UTC, jabbukka commented on docs/contribution.md
> +If there are no similar issues, you can create new issue [here](https://github.com/openinfradev/kustomize-helm-transformer/issues).
네 그럼 하나만 살려보겠습니다 ㅎㅎ

2021-01-04 08:20 UTC, jabbukka commented on docs/contribution.md
> +If there are no similar issues, you can create new issue [here](https://github.com/openinfradev/kustomize-helm-transformer/issues).
아래쪽 issue link를 삭제했습니다.

2021-01-04 09:29 UTC, Jaesang approved these changes

2021-01-04 09:41 UTC, bluejayKR requested changes

2021-01-04 09:41 UTC, bluejayKR commented on docs/contribution.md
> +Please read the [![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg)](code_of_conduct.md).
Code of Conduct를 https://github.com/openinfradev/community/blob/main/code-of-conduct.md 여기에 작성을 해 놓긴 했습니다만, 주신 링크가 더 내용이 많긴 하네요. 

1안: 우선은, HANU의 code of conduct를 링크를 거시고, 링크 걸어주신 https://www.contributor-covenant.org/version/2/0/code_of_conduct/ 기준으로 기존의 hanu code of conduct를 업데이트하면 좋지 않을까 합니다. 

2안: 우선은, HANU의 code of conduct를 링크를 거시고, "HANU에 속한 프로젝트들은 기본적으로 HANU code of conduct를 따르며, decapod 프로젝트에서는 추가로 "https://www.contributor-covenant.org/version/2/0/code_of_conduct/" 을 준수합니다"  라고 할 수도 있습니다. (이 경우는, 각 서브프로젝트별로 code of conduct가 좀 더 구체화 될 수 있게 되는거죠)

2021-01-04 09:41 UTC, bluejayKR commented on docs/code_of_conduct.md
> +[INSERT CONTACT METHOD].
컨택 정보를 제공해야 할텐데, community repo에 있는 code of conduct에는 다음과 같이 표현했습니다. 아래를 참조하여 업데이트 하면 좋겠습니다. 

Reporting 가이드라인
만약 커뮤니티 행동 강령을 위반하는 사례가 있다고 생각하신다면, Community의 이슈 (https://github.com/openinfradev/community/issues/new)로 등록하여 알려주시기 바랍니다. 직접적인 연락이 필요하시다면 다음 메일주소 (안재석, bluejay.ahn@gmail.com) 로 연락 주시기 바랍니다.

2021-01-04 10:13 UTC, bluejayKR commented on docs/code_of_conduct.md
> +[INSERT CONTACT METHOD].
https://www.contributor-covenant.org/ko/version/1/4/code-of-conduct/ 한글버전도 있군요. ^^

2021-01-05 02:15 UTC, jabbukka commented on docs/contribution.md
> +Please read the [![Contributor Covenant](https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg)](code_of_conduct.md).
말씀하신대로 각 프로젝트별로 다른 부분이 있을 수 있어서 2안으로 진행하는 것이 어떨까 싶습니다. 2안으로 변경하여 적용하겠습니다.

2021-01-05 04:51 UTC, jabbukka commented on docs/code_of_conduct.md
> +[INSERT CONTACT METHOD].
위 코멘트 내용과 함께 변경하였습니다.

2021-01-05 05:00 UTC, bluejayKR commented on docs/contribution.md
> +This project complies with the [Code of Conduct(KOR)](https://github.com/openinfradev/community/blob/main/code-of-conduct.md) of `HANU community`.
Please note that this project complies with the [Code of Conduct(KOR)] of HANU Community. Additionally, the project is released with an additional Contributor Code of Conduct [link to code of conduct v2.0..]. By participating in this project you agree to abide by its terms.

이 정도면 어떨까요?

2021-01-05 05:07 UTC, jabbukka commented on docs/contribution.md
> +This project complies with the [Code of Conduct(KOR)](https://github.com/openinfradev/community/blob/main/code-of-conduct.md) of `HANU community`.
넵 좋습니다 🙆‍♀️

2021-01-05 05:12 UTC, jabbukka commented on docs/ci.md
> +Here is list of Github Actions using in this repository.
수정하였습니다

2021-01-05 05:12 UTC, jabbukka commented on docs/contribution.md
> +This project complies with the [Code of Conduct(KOR)](https://github.com/openinfradev/community/blob/main/code-of-conduct.md) of `HANU community`.
수정하였습니다

2021-01-05 05:21 UTC, bluejayKR approved these changes

2021-01-05 05:22 UTC, merged